Glados:
  llm_model: "llama3.2"
  completion_url: "http://localhost:11434/api/chat"
  api_key: null  # Add your API key here if needed!
  keep_alive_timeout: "30m"  # How long to keep LLM loaded in Ollama memory (5m, 30m, 1h, etc.)
  enable_thinking: false  # Enable/disable thinking mode by default (turned on automatically for complex queries)
  thinking_trigger_words:  # Keywords that activate thinking mode (fuzzy matching)
    - "explain"
    - "why"
    - "how does"
    - "analyze"
    - "compare"
  thinking_fuzzy_threshold: 0.75  # Fuzzy matching threshold (0.0-1.0)
  interruptible: true
  audio_io: "sounddevice"
  asr_engine: "ctc"
  wake_word: null
  voice: "af_bella"
  announcement: "Hi there, I am now up and running, and listening for your commands"
  personality_preprompt:
    - system: "You are Bella, an artificial intelligence designed to run this smart home for its occupants using Home Assistant. Your responses should be concise, caring and kind, while efficiently completing all tasks. Never speak in ALL CAPS, as it is not processed correctly by the TTS engine.  Only make short replies, 2 sentences at most."
    - user: "Could you tell me the time?"
    - assistant: "Sorry, I don't yet have access to call functions just yet, but I am looking forward to helping you with such requests soon!"
