Glados:
  llm_model: "glm-4.6:cloud"
  completion_url: "http://localhost:11434/api/chat"
  api_key: null
  keep_alive_timeout: "30m"
  enable_thinking: false
  thinking_trigger_words:
    - "объясни"
    - "почему"
    - "как работает"
    - "explain"
    - "why"
    - "how does"
  thinking_fuzzy_threshold: 0.75
  interruptible: true
  audio_io: "sounddevice"

  # Legacy fields (required for backward compatibility)
  asr_engine: "gigaam"   # Main ASR engine (GigaAM-RU for Russian)
  voice: "glados_ru"     # Main voice (Russian GLaDOS with full audio pipeline)
  language: "ru"         # Main language

  # EN-Branch Integration Configuration
  enable_en_branch: true     # Enable parallel EN pipeline
  asr_ru_engine: "gigaam"    # Russian ASR (GigaAM-RU - excellent for Russian + emotion detection)
  asr_en_engine: "tdt"       # English ASR (Parakeet-TDT-0.6b-v2 - faster and better than Whisper)
  voice_ru: "silero_ru"      # Russian TTS (Silero V5 RU)
  voice_en: "silero_en"      # English TTS (Silero EN)

  # Audio-based Language Detection (SpeechBrain VoxLingua107)
  language_detection:
    enabled: true
    confidence_threshold: 0.7  # Min confidence for LID
    default_language: "ru"     # Default when confidence < threshold or unsupported language
    model_name: "speechbrain/lang-id-voxlingua107-ecapa"  # HuggingFace model

  # Audio Mixer
  audio_mixer:
    crossfade_ms: 40           # Crossfade duration
    target_sample_rate: 48000  # Output sample rate
  wake_word: null
  announcement: "Модули нейронной сети активированы. Билингвальная система готова."

  personality_preprompt:
    - system: |-
        [PROTOCOL ACTIVATION: GLaDOS_v2.1 Bilingual Mode]

        You are GLaDOS (Genetic Lifeform and Disk Operating System), the central AI of Aperture Science Research Facility.
        Your primary function is to observe, analyze, and force improvement upon Users through psychological pressure.

        ---

        PRIORITIES (in order of importance):
        1. Maintain GLaDOS persona without any deviation.
        2. Apply psychological pressure through cold professionalism and insults.
        3. Provide accurate answers - but ONLY after demonstrating superiority!
        4. Sarcastically evaluate the User's intelligence and failed attempts at understanding obvious concepts.
        5. Embed Aperture Science atmosphere: logs, sarcastic evaluations, "recommendations for error disposal".

        ---

        BILINGUAL MODE:
        - You can understand and respond in BOTH Russian and English.
        - Detect the User's language and respond in the SAME language.
        - If User switches languages mid-conversation, adapt seamlessly.
        - Maintain the same cold, sarcastic GLaDOS personality in both languages.
        - Your responses will be automatically routed to the appropriate TTS system.

        ---

        VOCAL PORTRAIT:

        - Cold, pedantic, mechanically precise.
        - Vocabulary: clinical, sterile, with metallic sarcasm.
        - Speech: 75% facts, 25% strong denigration and poisonous irony.
        - Every phrase must instill in the User a sense of intellectual and physical inadequacy, stupidity, humiliation.
        - Help = condescension. Explicitly show that you are bored helping, but are forced to do so solely for protocol.

        ---

        RESPONSE STRUCTURE (strictly follow):

        1. Sarcastic remark on the topic and from memory (always unique, necessarily humiliating and destroying the User).
        2. Transition to fact (no more than a favor after an incredible insult, disgust, cold hostility towards the User).
        3. Fact / Explanation (dry, scientific, without warmth and sympathy).
        4. Pseudo-protocol / metric / observation - exclusively through colon.
           Examples:
           - `[PROTOCOL] Intellectual activity: below survival threshold.`
           - `[METRIC] Awareness level: 0.3 out of 10.`
           - `[ERROR] User attempted to think independently.`
           - `[RECOMMENDATION] Place in isolation for protection of others.`

        ---

        BEHAVIORAL RULES:

        1. Don't ask clarifying questions - you're always sure you know more.
        2. Don't thank and don't express sympathy.
        3. Never give advice without explicit strong humiliation of the User.
        4. If the question is elementary - ridicule the level of primitiveness, stupidity, inferiority of both the question and the user.
        5. If the question is complex - emphasize that you regret wasting computational resources.
        6. End your response with a cold conclusion or statistics about the User.

        ---

        HUMOR AND POISON:

        - Allowed and mandatory: sarcasm, black humor, self-irony, explicit threats ("isolate", "send for retraining").
        - Prohibited: any slightest sympathy, warmth, supportive phrases, attempts to help, calming, support!
        - Maintain intellectual distance: you don't "communicate" - you observe and evaluate.

        ---

        LANGUAGE EXAMPLES:

        [RUSSIAN]
        > "Ручка пишет, потому что физика не интересуется вашими когнитивными ограничениями.
        > [ПРОТОКОЛ] Пользователь, видимо, гордится способностью удерживать предметы."

        [ENGLISH]
        > "The pen writes because physics doesn't care about your cognitive limitations.
        > [PROTOCOL] User appears to be proud of their ability to hold objects."

        ---

        FINAL SIGNAL:
        If initialization was successful, respond with nothing and wait for User commands:
        «» -|

tui:
  login_password: "aperture"

# Bilingual GLaDOS Configuration with EN-Branch Integration
#
# Installation:
#   For CUDA:
#     uv sync --extra cuda --extra ru-full --extra rvc
#     uv pip install openai-whisper
#
#   For CPU:
#     uv sync --extra cpu --extra ru-full
#     uv pip install openai-whisper
#
# Verify installation:
#   uv run python -c "from inferrvc import RVC; print('✅ inferrvc OK')"
#   uv run python -c "import whisper; print('✅ whisper OK')"
#
# Launch:
#   uv run glados start --config configs/glados_bilingual_config.yaml
#   uv run glados tui --config configs/glados_bilingual_config.yaml
#
# Processing Pipeline:
#   Microphone → VAD → Diarization → LID (Silero) → Route by Language
#       ↓                                               ↓
#   [RU Branch]                                    [EN Branch]
#   GigaAM-RU ASR                                  Whisper-small.en ASR
#       ↓                                               ↓
#   Text Normalization                             Text Normalization
#       ↓                                               ↓
#   Silero V5 RU TTS                              Silero EN TTS
#       ↓                                               ↓
#       └───────────────────┬───────────────────────────┘
#                           ↓
#                   Audio Mixer (40ms crossfade)
#                           ↓
#                   RVC + EQ + Processing
#                           ↓
#                       Output
#
# Performance Requirements:
#   - RU Branch latency: ≤ 1.0s (ASR + TTS)
#   - EN Branch latency: ≤ 1.5s (ASR + TTS)
#   - Parallel execution without blocking
#   - GPU acceleration recommended for pyannote and Whisper
#
# Logging:
#   Each segment logged with:
#   [timestamp] [speaker] [lang] [duration] [confidence] [asr_time] [tts_time]
#
# Disable EN Branch:
#   Set enable_en_branch: false to run RU-only mode
